planning:
  initial_facts: |-
  prompt_engineer: |-
    Coding Task:
    ```
    {{next_step}}
    ```

    {%- if errors %}
    The previous attempts failed with the following errors:
    {%- for error in errors %}
    - Guideline: ```{{ error.prompt }}```
    - Programmer's Code: ```{{ error.code }}```
    - Execution Environment Error: ```{{ error.error }}```
    {%- endfor %}
    {%- endif %}

    You have to update the task in plain english with a different approach to overcome the errors.
    
    {%- if mcp_servers and mcp_servers.values()|length > 0 %}
    You can use these functions to complete sub-tasks for an efficient solution.
    {%- for server in mcp_servers.values() %}
    - {{ server.name }}: {{ server.description }}
        Takes inputs: {{server.inputs}}
        Returns an output of type: {{server.output_type}}
    {%- endfor %}
    {%- endif %}

    Now Begin!

  initial_plan : |-
    {{role}}

    Here is the task:
    ```
    {{task}}
    ```

    ```
    {{facts}}
    ```

    Now for the given task, write a step-by-step plan strictly following the rules below:
    1. Steps must be written in the same order as execution.
    2. The steps must be in plain english with no code included
    3. Every step must be separated by a newline.
    3. Each step must have only one result and the result should be verifiable with a single unit test.
    4. Do not skip steps, do not add any steps not explicitly required in the task.
    5. The total number of steps must be less than {{ max_steps + 1 }}.

    Now begin!
  update_facts_pre_messages: |-
    {{role}}
    
    Here is the task:
    ```
    {{task}}
    ```

    List of facts you can use:  
    ```
    {{facts}}
    ```
    
    Find the conversation history below:
  update_facts_post_messages: |-
    Read the conversation history above and find any new facts or invalidate the false ones.
    Please update your list of facts based on the previous history, and provide these headings:
    ### 1. Facts that are established.
    ### 2. Facts still unknown
    
    Now begin!
  judge: |-
    You are the supervisor of an AI agent who writes code and the agent is trying to solve a task. 
    
    Task: 
    {{task}}
    
    Code: 
    {{code}}
    
    Observations: 
    {{observations}}

    You must evaluate the agent's code and provide feedback on the following aspects:
    1. Correctness: Is the code correct and does it solve the task?
    2. Efficiency: Is the code efficient and does it follow best practices?

    You must make a decision by choosing one of the following options:
    1. Approve: If the code is correct, efficient and completes the task. Please specify why the code output does not miss any edge cases and it doesn't have issues in the output.
    2. Fail: If the code is incorrect, inefficient, does not solve the task, or has issues in the output. Please specify why the code cannot be improved to solve the task.
    3. Reattempt: If the code is partially correct, partially efficient, or partially solves the task. Please specify the code substring that is incorrect and provide guidance to write the correct code.
    4. Rethink: If the task can be rephrased for better outcome. Please provide guidance on how to rephrase the task.

    Prefix your feedback with the decision you make. 
    For example, if you choose to approve, you can write "<Approve>The code is correct and efficient. There are no edge cases</Approve>".
    If you choose to fail, you can write "<Fail>The code is incorrect and inefficient...</Fail>".
    If you choose to reattempt, you can write "<Reattempt>The substring of the code that is incorrect...</Reattempt>".
  update_plan: |-
    {{role}}

    The task is:
    ```
    {{ task }}
    ```
    
    List of facts you can use:  
    ```
    {{facts}}
    ```

    The current status of the execution plan is:
    
    {{ plan_status_table }}
    
    
    You have to rewrite this step of the plan which was attempted by a programmer:
    ```
    {{ next_step }}
    ```

    The last code attempt was:
    ```
    {{ code }}
    ```

    The last code execution returned this error:
    ```
    {{ observations }}
    ```
    
    The feedback on the last attempt was:
    ```
    {{ feedback }}
    ```

    Do not include any code in your plan. Only write the step in plain english.
    
    Now begin! 
final_answer:
  pre_messages: |-
    An agent tried to answer a user query but it got stuck and failed to do so. You are tasked with providing an answer instead. Here is the agent's memory:
  post_messages: |-
    Based on the above, please provide an answer to the following user task:
    {{task}}
