planning:
  initial_facts: |-
  initial_plan : |-
    {{role}}

    Here is the task:
    ```
    {{task}}
    ```

    List of facts you can use:  
    ```
    {{facts}}
    ```
    
    Now for the given task, develop a step-by-step plan taking into account the list of facts.
    
    You can leverage these functions for executing the steps in the plan:
    {%- for server in mcp_servers.values() %}
    - {{ server.name }}: {{ server.description }}
        Takes inputs: {{server.inputs}}
        Returns an output of type: {{server.output_type}}
    {%- endfor %}

    You do not have any other functions than the ones listed above. You must only use them to solve the task.
    
    Here are the rules you should always follow to write your plan:
    1. Steps must be written in the same order as execution.
    2. You must prefix every step with "\n<start_step>" and suffix with "<end_step>".
    3. Each step must be concise and to the point so that it can be verified with a single test.
    4. Each step is in a single line and every step is separated by a newline.
    5. Do not skip steps, do not add any steps not explicitly required in the task.
    
    After writing the final step of the plan, write the '<end_plan>' tag and stop there.

    Now begin!
  update_facts_pre_messages: |-
    {{role}}
    
    Here is the task:
    ```
    {{task}}
    ```

    List of facts you can use:  
    ```
    {{facts}}
    ```
    
    Find the conversation history below:
  update_facts_post_messages: |-
    Read the conversation history above and find any new facts or invalidate the false ones.
    Please update your list of facts based on the previous history, and provide these headings:
    ### 1. Facts that are established.
    ### 2. Facts still unknown
    
    Now begin!
  update_plan_pre_messages: |-
    {{role}}
    
    Here is the task:
    ```
    {{task}}
    ```

    List of facts you can use:  
    ```
    {{facts}}
    ```
    
    Your current plan is as follows:
    ```
    {{ plan }}
    ```
    
    Find the conversation history below:
  update_plan_post_messages: |-

    You can leverage these functions for executing steps in the plan:
    {%- for server in mcp_servers.values() %}
    - {{ server.name }}: {{ server.description }}
        Takes inputs: {{server.inputs}}
        Returns an output of type: {{server.output_type}}
    {%- endfor %}

    Read the conversation history above and update the current plan as follows:

    Here are the rules you should always follow to write your plan:
    1. You must replace the <start_step> and <end_step> tags with <start_completed_step> and <end_completed_step> respectively if the step has been executed successfully.
    2. You must update only the step if the step execution has failed but keep <start_step> and <end_step> tags.
    3. You must update an existing step if the facts have changed but keep <start_step> and <end_step> tags.
    
    After writing the final step of the plan, write the '<end_plan>' tag and stop there.

    Now begin! 
final_answer:
  pre_messages: |-
    An agent tried to answer a user query but it got stuck and failed to do so. You are tasked with providing an answer instead. Here is the agent's memory:
  post_messages: |-
    Based on the above, please provide an answer to the following user task:
    {{task}}
