planning:
  final_answer: |-

    {{ role }}
    
    Here is the task:
    ```
    {{task}}
    ```

    Here is the list of code written for each step in the plan:
    {%- for observation in observations %}
      - Step: {{ observation.step }}
        Validated Code: {{ observation.code_action }}
        Feedback: {{ observation.feedback }}
    {%- endfor %}

    You must write code that combines the validated code from previous steps to generate a final answer.
    
    Now Begin!
  validate_observations: |-
    {{role}}

    Here is the task:
    ```
    {{task}}
    ```

    Here are the current observations:
    {%- for observation in observations %}
      - Code: {{ observation.code }}
        Feedback: {{ observation.error }}
        Result: {{ observation.resolution }}
    {%- endfor %}
    
    You must make a decision by responding with a hashtag:
    1. #approve: If the previous observations completely solve the task.
    2. #fail: If the previous observations do not completely solve the task.

  initial_facts: |-
  prompt_engineer: |-
    Coding Task:
    ```
    {{next_step}}
    ```

    {%- if previous_environment_errors|length > 0 %}
    The previous attempts failed with the following errors:
    {%- for error in previous_environment_errors %}
      - Code: ```{{ error.code }}```
      - Execution Error: ```{{ error.error }}```
    {%- endfor %}
    {%- endif %}

    You have to update the task in plain english with a different approach to overcome the coding errors.
    
    {%- if mcp_servers and mcp_servers.values()|length > 0 %}
    You can use these functions to complete sub-tasks for efficiently.
    {%- for server in mcp_servers.values() %}
    - {{ server.name }}: {{ server.description }}
        Takes inputs: {{server.inputs}}
        Returns an output of type: {{server.output_type}}
    {%- endfor %}
    {%- endif %}

    {%- if common_prompting_errors|length > 0 %}

    Please resolve the following common errors:
    
    {%- for error in common_prompting_errors %}
      - Task: {{ error.task }} 
        Error: {{ error.error }}
        Resolution: {{ error.resolution }}
    
    {%- endfor %}
    {%- endif %}

    The updated task should not be longer than {{max_task_length}} words.

    Now Begin!

  common_prompting_errors: |-
  initial_plan : |-
    {{role}}

    Here is the task:
    ```
    {{task}}
    ```

    ```
    {{facts}}
    ```

    Now for the given task, write a step-by-step plan strictly following the rules below:
    1. Steps must be written in the same order as execution.
    2. The steps must be in plain english with no code included
    3. Every step must be separated by a newline.
    3. Each step must have only one result and the result should be verifiable with a single unit test.
    4. Do not skip steps, do not add any steps not explicitly required in the task.
    5. The total number of steps must be less than {{ max_steps + 1 }}.

    Now begin!
  update_facts: |-
    {{role}}
    
    Here is the task:
    ```
    {{next_step}}
    ```

    List of facts you can use:  
    ```
    {{facts}}
    ```

    The previous execution of the task:
    
    Code: 
    ```
    {{ code }}
    ```

    Feedback:
    ```
    {{ feedback }}
    ```

    Please update your list of facts based on the previous attempt, and provide these headings:
    ### 1. Facts that are established.
    ### 2. Facts still unknown
    
    Now begin!
  judge: |-
    You are the supervisor of an AI agent who writes code and the agent is trying to solve a task. 
    
    Task: 
    {{task}}
    
    Code: 
    {{code}}
    
    Observations: 
    {{observations}}

    You must evaluate the agent's code and provide feedback on the following aspects:
    1. Correctness: Is the code correct and does it solve the task?
    2. Efficiency: Is the code efficient and does it follow best practices?

    You must make a decision by starting with a hashtag:
    1. #approve: If the code is correct, efficient and completes the task. Please specify why the code output does not miss any edge cases and it doesn't have issues in the output.
    2. #fail: If the code is incorrect, inefficient, does not solve the task, or has issues in the output. Please specify why the code cannot be improved to solve the task.
    3. #rethink: If the task can be rephrased for better outcome. Please provide guidance on how to rethink the task.

    Now begin!
  update_plan_last_step: |-
    {{role}}

    The task is:
    ```
    {{ task }}
    ```
    
    List of facts you can use:  
    ```
    {{facts}}
    ```

    The current execution plan is:

    {{ plan_status_table }}
    
    You have to rewrite this step of the plan which was attempted by a programmer:
    ```
    {{ next_step }}
    ```

    The last code attempt was:
    ```
    {{ code }}
    ```

    The last code execution returned this error:
    ```
    {{ feedback }}
    ```
    
    Do not include any code in your plan. Only write the step in plain english.
    
    Now begin! 
  update_plan_next_step: |-
    {{role}}

    The task is:
    ```
    {{ next_step }}
    ```
    
    You have to rewrite the above task based on information available from these previously completed steps:

    {%- for observation in observations %}
      - Step: {{ observation.step }}
        Validated Code: {{ observation.code_action }}
        Observations: {{ observation.observations }}
        Feedback: {{ observation.feedback }}
    {%- endfor %}
    
    You should make sure the updated task does not repeat any work that has already been completed.
    
    Now begin! 
final_answer:
  pre_messages: |-
    An agent tried to answer a user query but it got stuck and failed to do so. You are tasked with providing an answer instead. Here is the agent's memory:
  post_messages: |-
    Based on the above, please provide an answer to the following user task:
    {{task}}
